export const asciiLetters = String.raw`
                                                                                                                                                                                                                                                
                                                                                                                                               ''_[11CCY}?>/;_.'                                         '''-.'  '~.                            
                                                                                                                                              ''.;y%m99K999mmqXe'                                      '':~[sIsT1Yr.;:..''..                    
                                                                                                                                          ':[>].!TVPm9OO99mmEPS2.                                     ''_}Iaey5$bVIIXSeeVes/.                   
                                                                                                                                     ''''''-!>c~>YIq9KDDK9OD9$XaL'                                   '--/1SIeabZyCIemDOmX2{'_.                  
                                                                                                                                      ''    ''''_>CX99KKKKO99m%Sa1'                                '-r}Cyus}CyqqExeXEKDg9e?{yVCi;_!'            
                                                                                                                                        '' ''.'';}hE99mXq%mmmqXa2C;                              ''-=}>7vviuZmam#gD##9bP9O$PmK9m%ShI+!='        
                                                                                                                                 '''''.''_';+;[~[CaXq$eCh2599mq9mXs~''                           ':}C1:_!yXSIaS9D9g#R#D###mEqK9gD9m$Xwi'''    ''
                                                                                                                                       ''''''.,,r}C5b1r+vcC99mEPShIs>>_'                          -z1CTr~uZaIye{59g####gh1VDRRRR##gDKE5YyC[viTe{
                                                                                                                              ''-:'''''-'''':-.,;cuVP1r|uqymmmqm99SZ5eui-                       '''lIICCu};yyyeE9mPmqgD5yS#88888RRRR#g9m9maaSee2
                                                                                                                             ''-:':..'_?s}~YIer''-~;]j+!+iSmmm$EmEmEm$%ZI'                 ':;;|LxYyw2sYsv}syC5ea$Dgg#DZ9#RR8888gg8888RR#g9m99$q
                                     '''         ''''                                                                      '       ''';{IyC*Cy}_:;iYyu,':7%q$qqPXSZXX$Xayuc,'               .:;7eVyyaZ1ssyya$qDDDKg###RRRRR##888000000#####DDDK8
                                   ''-;,.-::.'''.:~":_--...                                                              ''''''  ''.'.~rr~.i7eIyCeVXbbY-_;VCSZh%ZPEX%m$$bPZIs.             'r[i1ISb%a$KKO##mmg####RRRRRR8R9ZPRRR800008#88##g888B
                                 '.;"]ssxsYjc;:!;~sY}j?Ti>;_'                                                        ''''--_:~!_,,-;.'--.' '''''.:+sea5u""~rsSXq$b$%XXXXS5VheIs:'         '.!-.vS5Vis59RRR88R#R880000880008R00B080000008RR880BBB
                              '_-~??LICyu2yc||j;=hqm99DDDmYs;'                                                      '' '''  '.-~v~-'.'-.~''''''.:r}eSXXu~~;sXX%bPhZPPXSSSaawCCysLi+-''    '-";7eZh+ybDDR8888008800008888800BBBBBB000880R80BBBBBB
                             _:!=is?uV9mX%SawYXXmqm9wC#88#b5a{''                                                          '-|;=+;  '   '''''.,"r>7IhZZ5h]!!;uyrsCIVSSZSZ55S5hheyIC"'~Vy'+II7CVXuVm$wDR8000000880BBBB088088000000008880000B0BBBBB
                          ':_+iIYYP9#RRg####RR###RDKmwKPuVZ95Xyi-'                            '                  '''..-''-,!cl,''.:;~_-,-:c*Yc|c{[uhwS5h[+~|*yzvsCehVeyIyeVw2y*yeC'':7DXhCwX99Dg9999#8000000B00B0BB088888000008BB00800R#9qqRBBBB
                      ''~]Lj>LymOgDRRR#mD#g800888RDXPPy;[1LilII-'    '''''     '   ' '''''  '''  ''  ' ''''''' ''''''::''.:~~:''-:r|cs77svyhy{sisy2aaZZwr;}2ahI2aaZVI1ssxxIyu**s{[''1R00Db9K#8008R88g#88000WBBBWR88088800000000000000000880BBBBB
'         ''''      '-/|eXm$PqDg#9hm9mR0BB0000#08880800Rgqq1-'''''''_!+++ir~'  ''  ''''''   '''    '-:...--..-''.'  '''  '   '.'''   -uyeeeeyyyIs~:~rveeeu]]r];+?i|;+|c?y*CIsvxTc~~X8BBB0000BB0DSwCXPa#R000MMWWW8B0088#00000B0BBB0BBBBWBWBBBBBBB
'''''''' '''''''''''.;}S$hyXeS9RRZ##O0BMMMMMMBWWB0000MM08RDe:'':wuueXmDR#g##m>'     ''''''     '''         '-' '         '          '!zIyyyI1T1CT|::|uIyyy+/;:iry>=;;;IhCyhXEP5j!+S8BBBBBBBBB0#7auXZ9DRR0BBMMMMWW0RR#80000008#BB00BBBBBBBBBBBBBB
''''''''''''''  '''''+hVS5SODD##R8B8008MM@@@WWM@@@@@@MWB0089y='.PRRRR#00B0#Xmc'     '.' '''''''''''''''   '.:'           '         ''+?iii>;"[;s}:_:r{c{7s/''-D0B09i"[CX#mKq0RDbmaDRWWBBBBBBB09Z5DgRR800BBWW088BB08R#R8000008#R00BBBBB0000000BBB
'''  '''''''   ''.-''eSv*}Iyq88080BBB0B@@@@@@N@NNNNNN@MB0808RX;,58D5ZXRmR00RY:_-''''-:.'.---''.--'''.,_-'''._            '   '    '!;+]i>r:.~~;?c;~":~;r=Is'_Z0WWBWB#Bg8BWWBWWBB#R90BBBBB00BB0ScPmgR80R0BB000000000888000008gggKg000#D9hYXmaPwmm
'''' '''''     ''-__-;|+?PDPE8#R00BBWMM@@@NNNN@@@@@@@@MW08088#w[{1ey$8###R88R{_-''''''-----.''._.'''...-_,.-.            '   '  ''-!+;~~"!--_,:~;;"_,+vv{z::q0BWWWWWMMMWWWMWWWWBB0RBBBBBB0000B0R8R00WWWBBB000008RD8888000BBB008RRmECv+"'''_--.''
'''' '''  ''''''.,:::!!~'rm#R0000000BWWMM@@@@@MMBWM0Rme?[>S92?~:;lyqR000BB0Oe!''.-''''''''-_:~v7]r.'-'._:_-.'' ''               '''--''.-,-'''.-_,,_!;]>+|;X0BWWMWWMMMWWWWWWWWWWWWWWBBBBBBBBBBBBB00BWWWWBBBB000R#R8088000000ggX]z:''''''-!~!:!_;
'--''' ' ''-:+;i]i{{;~!:-_;ySXZIa9RR888880BWB0888RDx_.''''-_.-.-_cK#88g9#8RXY_''_    '  .:"sueehhVC7].-..''-....''''' '''''''  ''-'-.-:;~++;:'':!_i}jaP9g80BBWWWWMWMMMWMMWWWBWWBBBBWWBBBBWBBBBBBB00BWWWBBBBB00RmYbgR88R#RgXh>-:-.'._";+?v1Cyeeeh
'''''''',![*Yi}uCyIyj_,',"ri?+;[cwaIxImg9DR88R#Dg1~_,''' ''.'''''.aaZVh]:~.''''--_,.'  ':/?z}|++{>~!l>r~'':ii?+_''.''''.+ivv~+jxuICi-:vssuuC~-[9#RK800BBWWWWWWWWMWWMWWWMMWWWBBBBBBBWWBWBBBBBBBBWBB0WWWBBB0008##5''VSRge19ZVz"-_~|>{sYI22h5Pm9999
''''-.:l}suyeCC*uCIy1sjlr|;~;;~:_-.-::rcchmSSaame'''   ''''''  ''-v''      ''''_:~==;_-.':~r;~[uyyCCV2Ie7:]>[~.    '':}y$D#mDR88000088R80008weRBBMMMWWWWWWWMWWWWMWWWWWWWMBWWBBBBBMWWWWWWBBBBBBBWBBBBB0R8Rgbe1IeX] i]qK>'LV]vx7Luy5Pq$mm99mm9g#RR
'''''-;>l1IIuuu7T*Yi;":-.''....''''''_;;:=e;"_1w:   ''    '''   .{'   ''.,,''',-''''''-!;|/;::[v1IhmES5y}=/;:.'   .{VOR8000B0BBBBBBBWWWWWWWWWRBWWMMMWWWWWWWWWWMWWWWWWWBWWWBBBBBBBWBBBBBBBWB080000RDDgmi;]+':'..!:''"~yy-:I5Pm9ODgg##########RRR8
"_-.''''-:+;;:--,..,-...''...''.'''''''''ie[]~I1'           '._;u:,_~>aPm9OKKK9999999KDg#RR88880000000Rg9$%VyY~~]zE#80BBBBBBBBBBBBBBMMWWWWWWMWWWWWWWWWWWBBBBBWWBBBBBBBBBBBBBBBBBBWWBBBWBB000$CuCIc~![:'''''''''''''.~sm$ePm9gRRRRRRRRRRRRRRRRRRR
`;

export default asciiLetters;
