/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.12.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export interface InstantiateMsg {
  owner: string;
}
export type ExecuteMsg = {
  add: {
    native_coins: [string, number][];
  };
} | {
  register: {
    native_coins: [string, number][];
  };
} | {
  remove: {
    native_coins: string[];
  };
} | {
  propose_new_owner: {
    expires_in: number;
    owner: string;
  };
} | {
  drop_ownership_proposal: {};
} | {
  claim_ownership: {};
};
export type QueryMsg = {
  config: {};
} | {
  native_token: {
    denom: string;
  };
} | {
  native_tokens: {
    limit?: number | null;
    start_after?: string | null;
  };
};
export type Addr = string;
export interface Config {
  owner: Addr;
}
export interface CoinResponse {
  decimals: number;
  denom: string;
}
export type ArrayOfCoinResponse = CoinResponse[];